### ISSUE TITLE
Handle invalid fetch responses from Mynewsdesk

### ISSUE THREAD

**Issue by cnrdh** [akvaplan-niva/akvaplan_fresh#185]
```js
An error occurred during route handling or page rendering. TypeError: Value is not a valid ByteString
    at makeException (ext:deno_webidl/00_webidl.js:90:10)
    at converters.ByteString (ext:deno_webidl/00_webidl.js:418:11)
    at Array.record<ByteString, ByteString> (ext:deno_webidl/00_webidl.js:936:28)
    at Array.webidl.converters.HeadersInit (ext:deno_fetch/20_headers.js:457:63)
    at Array.webidl.converters.ResponseInit_fast (ext:deno_fetch/23_response.js:470:41)
    at new Response (ext:deno_fetch/23_response.js:310:50)
    at GET (file:///src/routes/mynewsdesk-articles/[slug].tsx:25:12)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Server.handler (https://deno.land/x/fresh@1.2.0/src/server/context.ts:388:14)
    at async Server.#respond (https://deno.land/std@0.190.0/http/server.ts:299:18)

**Comment by cnrdh** [comment]
These still occur in production: 
![image](https://github.com/akvaplan-niva/akvaplan_fresh/assets/35185/94279047-7d2d-44f6-b6cf-8b591f6a87dc)
