### ISSUE TITLE
Stop using live mynewsdesk search

### ISSUE THREAD

**Issue by cnrdh** [akvaplan-niva/akvaplan_fresh#302]
For example, from a person's homepage:
not just because of 500s…

```js
500
error sending request for url (https://www.mynewsdesk.com/services/pressroom/search/{key}?format=json&type_of_media=news&strict=true&limit=64&query={family}&sort=created): connection error: connection reset
TypeError: error sending request for url (https://www.mynewsdesk.com/services/pressroom/search/{key}?format=json&type_of_media=news&strict=true&limit=64&query=Fieler&sort=created): connection error: connection reset
    at async mainFetch (ext:deno_fetch/26_fetch.js:170:12)
    at async fetch (ext:deno_fetch/26_fetch.js:391:7)
    at async searchMynewsdesk (file:///src/services/mynewsdesk.ts:312:20)
    at async multiSearchMynewsdesk (file:///src/services/mynewsdesk.ts:381:25)
    at async newsOnPerson (file:///src/services/people.ts:22:17)
    at async GET (file:///src/routes/akvaplanist.tsx:174:9)
    at async handler (https://deno.land/x/fresh@1.6.3/src/server/context.ts:288:14)
    at async ext:deno_http/00_serve.js:455:18

**Comment by cnrdh** [comment]
Fixed by #325 – live search are still enabled to retrieve fresh Mynewsdesk content (news, pr, videos,images,docs).
