### ISSUE TITLE
People crash (500)

### ISSUE THREAD

**Issue by cnrdh** [akvaplan-niva/akvaplan_fresh#392]
https://akvaplan.no/no/folk/name/Falk-Petersen/S.

**Comment by cnrdh** [comment]
```js
TypeError: Cannot read properties of undefined (reading 'some')
    at file:///src/services/people.ts:69:10
    at Array.filter (<anonymous>)
    at pubsFromPerson (file:///src/services/people.ts:67:6)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async pubsFromPersonGroupedByYear (file:///src/services/people.ts:82:5)
    at async GET (file:///src/routes/akvaplanist.tsx:226:9)
    at async handler (https://deno.land/x/fresh@1.6.8/src/server/context.ts:293:14)
    at async ext:deno_http/00_serve.ts:364:18

**Comment by cnrdh** [comment]
Works now, but should it 301 / 404 ?
